export const candidateShortlist = [
  {
    photoUrl: "https://media.licdn.com/dms/image/D5603AQEZpEGnGpQHpg/profile-displayphoto-shrink_100_100/0/1673581566105?e=1683763200&v=beta&t=7RKSOQ0tdNO3XZPaenyqo-6OTnNDQR2-iqs5OLUBS3k",
    fullName: 'John Doe',
    summary:
      'San Francisco-based software engineer with 85% match, skilled in Java, Python, and JavaScript. Strongly ranked in education, company fit, and technical skills.',
    percentageMatch: 85,
    currentTitle: 'Software Engineer',
    currentCompany: 'ABC Inc.',
    location: 'San Francisco, CA',
    linkedinUrl: 'https://www.linkedin.com/in/john-doe',
    websiteUrl: 'https://johndoe.com',
    githubUrl: 'https://github.com/johndoe',
    twitterUrl: 'https://twitter.com/johndoe',
    resumeUrl: 'https://johndoe.com/resume.pdf',
    coverLetterUrl: 'https://johndoe.com/cover-letter.pdf',
    rankings: {
      educationPercentage: 90,
      experiencePercentage: 80,
      technicalSkillsPercentage: 85,
      objectivesPercentage: 75,
      companyFitPercentage: 90,
      locationFitPercentage: 80,
    },
    desiredCompensation: 120000,
    interpersonalCharacteristics: [
      'Team player',
      'Communicative',
      'Detail-oriented',
    ],
    technicalSkills: ['Java', 'Python', 'JavaScript'],
  },
  {
    photoUrl: "https://media.licdn.com/dms/image/D5603AQH39CkswM5XHw/profile-displayphoto-shrink_100_100/0/1668803767494?e=1683763200&v=beta&t=XSPGW7HQlauJQhcf0leB15YFRHpZfJYEzrYL1fQOTHY",
    fullName: 'Jane Smith',
    summary:
      'New York-based data scientist with a 90% match and expertise in R, SQL, and Python. Strongly ranked in education, technical skills, and company fit.',
    percentageMatch: 90,
    currentTitle: 'Data Scientist',
    currentCompany: 'XYZ Corp.',
    location: 'New York, NY',
    linkedinUrl: 'https://www.linkedin.com/in/jane-smith',
    websiteUrl: 'https://janesmith.com',
    githubUrl: 'https://github.com/janesmith',
    twitterUrl: 'https://twitter.com/janesmith',
    resumeUrl: 'https://janesmith.com/resume.pdf',
    coverLetterUrl: 'https://janesmith.com/cover-letter.pdf',
    rankings: {
      educationPercentage: 95,
      experiencePercentage: 85,
      technicalSkillsPercentage: 90,
      objectivesPercentage: 80,
      companyFitPercentage: 95,
      locationFitPercentage: 85,
    },
    desiredCompensation: 150000,
    interpersonalCharacteristics: [
      'Independent worker',
      'Analytical',
      'Problem solver',
    ],
    technicalSkills: ['R', 'SQL', 'Python'],
  },
  {
    photoUrl: "https://media.licdn.com/dms/image/C5603AQGjMFxCSnPyww/profile-displayphoto-shrink_100_100/0/1624585270569?e=1683763200&v=beta&t=rcCh_HFy305wp9NSQREid_HpPkYV_guRhOFS4JaOIaw",
    fullName: 'David Lee',
    summary:
      'Seattle-based product manager with 80% match, skilled in Agile methodology, product strategy, and market research. Strongly ranked in experience, objectives, and company fit.',
    percentageMatch: 80,
    currentTitle: 'Product Manager',
    currentCompany: 'LMN Corp.',
    location: 'Seattle, WA',
    linkedinUrl: 'https://www.linkedin.com/in/david-lee',
    websiteUrl: 'https://davidlee.com',
    githubUrl: 'https://github.com/davidlee',
    twitterUrl: 'https://twitter.com/davidlee',
    resumeUrl: 'https://davidlee.com/resume.pdf',
    coverLetterUrl: 'https://davidlee.com/cover-letter.pdf',
    rankings: {
      educationPercentage: 85,
      experiencePercentage: 90,
      technicalSkillsPercentage: 80,
      objectivesPercentage: 85,
      companyFitPercentage: 80,
      locationFitPercentage: 90,
    },
    desiredCompensation: 130000,
    interpersonalCharacteristics: ['Leadership', 'Collaborative', 'Creative'],
    technicalSkills: [
      'Agile methodology',
      'Product strategy',
      'Market research',
    ],
  },
  {
    photoUrl: "https://media.licdn.com/dms/image/C4D03AQGTxhDFEjXJNw/profile-displayphoto-shrink_100_100/0/1516259572122?e=1683763200&v=beta&t=9aDKco1m53ktuGsbAZHTpc9K9RVT86D1Iu6__rPLpvk",
    fullName: 'Emily Chen',
    summary:
      'Chicago-based marketing manager with 75% match, skilled in social media marketing, content creation, and email marketing. Strongly ranked in objectives and education.',
    percentageMatch: 75,
    currentTitle: 'Marketing Manager',
    currentCompany: 'PQR Inc.',
    location: 'Chicago, IL',
    linkedinUrl: 'https://www.linkedin.com/in/emily-chen',
    websiteUrl: 'https://emilychen.com',
    githubUrl: 'https://github.com/emilychen',
    twitterUrl: 'https://twitter.com/emilychen',
    resumeUrl: 'https://emilychen.com/resume.pdf',
    coverLetterUrl: 'https://emilychen.com/cover-letter.pdf',
    rankings: {
      educationPercentage: 80,
      experiencePercentage: 75,
      technicalSkillsPercentage: 70,
      objectivesPercentage: 80,
      companyFitPercentage: 75,
      locationFitPercentage: 80,
    },
    desiredCompensation: 110000,
    interpersonalCharacteristics: [
      'Excellent communicator',
      'Strategic thinker',
      'Customer-focused',
    ],
    technicalSkills: [
      'Social media marketing',
      'Content creation',
      'Email marketing',
    ],
  },
  {
    photoUrl: "https://media.licdn.com/dms/image/C4E03AQEYJMy3LzOV5A/profile-displayphoto-shrink_100_100/0/1662141974629?e=1683763200&v=beta&t=-x_3Z-wSAGGa5NszOXI9tzJbMHz3sZgfmmxxVcoS7H8",
    fullName: 'Michael Johnson',
    summary:
      'Austin-based software developer with 95% match, skilled in Java, C++, Python, and Agile methodology. Strongly ranked in education, experience, technical skills, and location fit.',
    percentageMatch: 95,
    currentTitle: 'Software Developer',
    currentCompany: 'EFG Corp.',
    location: 'Austin, TX',
    linkedinUrl: 'https://www.linkedin.com/in/michael-johnson',
    websiteUrl: 'https://michaeljohnson.com',
    githubUrl: 'https://github.com/michaeljohnson',
    twitterUrl: 'https://twitter.com/michaeljohnson',
    resumeUrl: 'https://michaeljohnson.com/resume.pdf',
    coverLetterUrl: 'https://michaeljohnson.com/cover-letter.pdf',
    rankings: {
      educationPercentage: 95,
      experiencePercentage: 95,
      technicalSkillsPercentage: 95,
      objectivesPercentage: 90,
      companyFitPercentage: 90,
      locationFitPercentage: 95,
    },
    desiredCompensation: 140000,
    interpersonalCharacteristics: [
      'Detail-oriented',
      'Team player',
      'Proactive',
    ],
    technicalSkills: ['Java', 'C++', 'Python', 'Agile methodology'],
  },
  {
    photoUrl: "https://media.licdn.com/dms/image/C5603AQGrucd0aBJV-g/profile-displayphoto-shrink_100_100/0/1654626129550?e=1683763200&v=beta&t=V66OSp7wnQtnBur0-B9UqF3CM8DEEeL7g9ETb7Tl_AM",
    fullName: 'Amanda Wong',
    summary:
      'Los Angeles-based UX designer with 80% match, skilled in Sketch, Adobe Creative Suite, and user research. Strongly ranked in education and experience.',
    percentageMatch: 80,
    currentTitle: 'UX Designer',
    currentCompany: 'HIJ Inc.',
    location: 'Los Angeles, CA',
    linkedinUrl: 'https://www.linkedin.com/in/amanda-wong',
    websiteUrl: 'https://amandawong.com',
    githubUrl: 'https://github.com/amandawong',
    twitterUrl: 'https://twitter.com/amandawong',
    resumeUrl: 'https://amandawong.com/resume.pdf',
    coverLetterUrl: 'https://amandawong.com/cover-letter.pdf',
    rankings: {
      educationPercentage: 85,
      experiencePercentage: 80,
      technicalSkillsPercentage: 75,
      objectivesPercentage: 80,
      companyFitPercentage: 80,
      locationFitPercentage: 85,
    },
    desiredCompensation: 120000,
    interpersonalCharacteristics: ['Creative', 'Collaborative', 'Empathetic'],
    technicalSkills: ['Sketch', 'Adobe Creative Suite', 'User research'],
  },
  {
    photoUrl: "https://media.licdn.com/dms/image/C4E03AQEB2_vfsTJw7g/profile-displayphoto-shrink_100_100/0/1581359050355?e=1683763200&v=beta&t=0RClbzFzIyf_QQV4-Z3Gxy8bYEE5ZmMugXfel_5mbcc",
    fullName: 'Steven Park',
    summary:
      'San Diego-based project manager with 70% match, skilled in project management, Agile methodology, and Microsoft Project. Strongly ranked in experience and objectives.',
    percentageMatch: 70,
    currentTitle: 'Project Manager',
    currentCompany: 'LMN Corp.',
    location: 'San Diego, CA',
    linkedinUrl: 'https://www.linkedin.com/in/steven-park',
    websiteUrl: 'https://stevenpark.com',
    githubUrl: 'https://github.com/stevenpark',
    twitterUrl: 'https://twitter.com/stevenpark',
    resumeUrl: 'https://stevenpark.com/resume.pdf',
    coverLetterUrl: 'https://stevenpark.com/cover-letter.pdf',
    rankings: {
      educationPercentage: 75,
      experiencePercentage: 80,
      technicalSkillsPercentage: 70,
      objectivesPercentage: 75,
      companyFitPercentage: 70,
      locationFitPercentage: 80,
    },
    desiredCompensation: 100000,
    interpersonalCharacteristics: [
      'Organized',
      'Excellent communicator',
      'Leadership',
    ],
    technicalSkills: [
      'Project management',
      'Agile methodology',
      'Microsoft Project',
    ],
  },
  {
    photoUrl: "https://media.licdn.com/dms/image/C5603AQHsjLMOVtEskw/profile-displayphoto-shrink_100_100/0/1648076690891?e=1683763200&v=beta&t=3AOvooPIf1hsP79tI-4PbuEYu3tr_fJOpmveQ9gHoCM",
    fullName: 'Rachel Lee',
    summary:
      'Boston-based data analyst with 85% match, skilled in SQL, Python, and Tableau. Strongly ranked in education, technical skills, and company fit.',
    percentageMatch: 85,
    currentTitle: 'Data Analyst',
    currentCompany: 'NOP Inc.',
    location: 'Boston, MA',
    linkedinUrl: 'https://www.linkedin.com/in/rachel-lee',
    websiteUrl: 'https://rachellee.com',
    githubUrl: 'https://github.com/rachellee',
    twitterUrl: 'https://twitter.com/rachellee',
    resumeUrl: 'https://rachellee.com/resume.pdf',
    coverLetterUrl: 'https://rachellee.com/cover-letter.pdf',
    rankings: {
      educationPercentage: 90,
      experiencePercentage: 80,
      technicalSkillsPercentage: 85,
      objectivesPercentage: 80,
      companyFitPercentage: 85,
      locationFitPercentage: 80,
    },
    desiredCompensation: 110000,
    interpersonalCharacteristics: [
      'Detail-oriented',
      'Analytical',
      'Problem solver',
    ],
    technicalSkills: ['SQL', 'Python', 'Tableau'],
  },
  {
    photoUrl: "https://media.licdn.com/dms/image/D5603AQEbO9AmD5dZQg/profile-displayphoto-shrink_100_100/0/1674573600714?e=1683763200&v=beta&t=J4PSfgl59hC1_SI71raDz7R1yvGFA5HkHfN64XDy__o",
    fullName: 'Karen Kim',
    summary:
      'Denver-based HR coordinator with 75% match, skilled in recruiting, employee relations, and performance management. Strongly ranked in education and objectives.',
    percentageMatch: 75,
    currentTitle: 'HR Coordinator',
    currentCompany: 'QRS Corp.',
    location: 'Denver, CO',
    linkedinUrl: 'https://www.linkedin.com/in/karen-kim',
    websiteUrl: 'https://karenkim.com',
    githubUrl: 'https://github.com/karenkim',
    twitterUrl: 'https://twitter.com/karenkim',
    resumeUrl: 'https://karenkim.com/resume.pdf',
    coverLetterUrl: 'https://karenkim.com/cover-letter.pdf',
    rankings: {
      educationPercentage: 80,
      experiencePercentage: 75,
      technicalSkillsPercentage: 70,
      objectivesPercentage: 75,
      companyFitPercentage: 75,
      locationFitPercentage: 80,
    },
    desiredCompensation: 90000,
    interpersonalCharacteristics: [
      'People-oriented',
      'Organized',
      'Approachable',
    ],
    technicalSkills: [
      'Recruiting',
      'Employee relations',
      'Performance management',
    ],
  },
  {
    photoUrl: "https://media.licdn.com/dms/image/C5603AQFGMg_rn78lvA/profile-displayphoto-shrink_100_100/0/1642885760590?e=1683763200&v=beta&t=EkAoXkejKlph0pVzHU66sh4kNqLklvygaB50z-jS3aU",
    fullName: 'Daniel Kim',
    summary:
      'Houston-based full stack developer with 80% match, skilled in Node.js, React, MongoDB, and JavaScript. Strongly ranked in education, technical skills, and location fit.',
    percentageMatch: 80,
    currentTitle: 'Full Stack Developer',
    currentCompany: 'STU Inc.',
    location: 'Houston, TX',
    linkedinUrl: 'https://www.linkedin.com/in/daniel-kim',
    websiteUrl: 'https://danielkim.com',
    githubUrl: 'https://github.com/danielkim',
    twitterUrl: 'https://twitter.com/danielkim',
    resumeUrl: 'https://danielkim.com/resume.pdf',
    coverLetterUrl: 'https://danielkim.com/cover-letter.pdf',
    rankings: {
      educationPercentage: 85,
      experiencePercentage: 80,
      technicalSkillsPercentage: 80,
      objectivesPercentage: 75,
      companyFitPercentage: 80,
      locationFitPercentage: 85,
    },
    desiredCompensation: 120000,
    interpersonalCharacteristics: [
      'Self-motivated',
      'Collaborative',
      'Problem solver',
    ],
    technicalSkills: ['Node.js', 'React', 'MongoDB', 'JavaScript'],
  },
]
